singleItemScoreValue: 50
bingoScoreValue: 500
dropReplace:
  "IRON_ORE": "IRON_INGOT"
  "GOLD_ORE": "GOLD_INGOT"
  "COPPER_ORE": "COPPER_INGOT"
  "DEEPSLATE_IRON_ORE": "IRON_INGOT"
  "DEEPSLATE_GOLD_ORE": "GOLD_INGOT"
  "DEEPSLATE_COPPER_ORE": "COPPER_INGOT"